version: '3'
services:
  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: hook:prod
    command: php-fpm
    container_name: api
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: api
      SERVICE_TAGS: dev
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: hook
      DB_USERNAME: admin
      DB_PASSWORD: admin
      QUEUE_CONNECTION: database
      JWT_SECRET: f5vx7U0mojw7r6L3JzlKwGhjFT5tyA5Sz01RGejw3pQwmXYVzBbkPYz2cqEzA3VP
      HOOK_TIMEOUT: 10
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: hook:prod
    command: /usr/bin/supervisord
    container_name: worker
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: worker
      SERVICE_TAGS: dev
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: hook
      DB_USERNAME: admin
      DB_PASSWORD: admin
      QUEUE_CONNECTION: database
      HOOK_TIMEOUT: 10
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8000:80"
    networks:
      - app-network
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: hook
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: "12345678"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
