version: '3'
services:
  api:
    image: hook:0.0.1
    container_name: api
    restart: unless-stopped
    tty: true
    env_file:
      - /etc/hook/.env.app-secret
    environment:
      SERVICE_NAME: api
      SERVICE_TAGS: dev
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: hook
    working_dir: /var/www
    networks:
      - hook-network
  worker:
    image: hook:0.0.1-worker
    container_name: worker
    restart: unless-stopped
    tty: true
    env_file:
      - /etc/hook/.env.app-secret
    environment:
      SERVICE_NAME: worker
      SERVICE_TAGS: dev
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: hook
    working_dir: /var/www
    networks:
      - hook-network
  scheduler:
    image: hook:0.0.1-scheduler
    container_name: scheduler
    restart: unless-stopped
    tty: true
    env_file:
      - /etc/hook/.env.app-secret
    environment:
      SERVICE_NAME: scheduler
      SERVICE_TAGS: dev
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: hook
    working_dir: /var/www
    networks:
      - hook-network
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8000:80"
    networks:
      - hook-network
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: hook
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - hook-network
    volumes:
      - mysql-data:/var/lib/mysql
networks:
  hook-network:
    driver: bridge
volumes:
  mysql-data:
    external: true
